# Generated by Django 6.0.4 on 2026-04-27 17:38

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_creation', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('niveau', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceFederation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AffiliationAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_affiliation', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('radiee', 'Radiée')], default='active', max_length=20)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('montant_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='gestion.association')),
            ],
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(default='actif', max_length=20)),
                ('date_adhesion', models.DateField(auto_now_add=True)),
                ('type_membre', models.CharField(choices=[('actif', 'Actif'), ('honoraire', 'Honoraire')], default='actif', max_length=20)),
                ('role', models.CharField(choices=[('membre', 'Membre'), ('president', 'Président')], default='membre', max_length=20)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhesions', to='gestion.association')),
            ],
        ),
        migrations.CreateModel(
            name='CotisationAssociationMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee', models.PositiveIntegerField()),
                ('mois', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('montant_attendu', models.DecimalField(decimal_places=2, default=20, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('partiel', 'Partiel'), ('impaye', 'Impayé')], default='en_attente', max_length=20)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('mode_paiement', models.CharField(blank=True, choices=[('virement', 'Virement'), ('cash', 'Espèces'), ('cheque', 'Chèque'), ('carte', 'Carte bancaire')], max_length=20)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations_mensuelles', to='gestion.affiliationassociation')),
            ],
            options={
                'ordering': ['-annee', '-mois'],
            },
        ),
        migrations.CreateModel(
            name='DossierRapatriement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_deces', models.DateField()),
                ('lieu_deces', models.CharField(max_length=200)),
                ('pays_deces', models.CharField(blank=True, max_length=100)),
                ('destination_rapatriement', models.CharField(max_length=200)),
                ('personne_contact', models.CharField(blank=True, max_length=200)),
                ('telephone_contact', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('refuse', 'Refusé')], default='ouvert', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.affiliationassociation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContributionDecesAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant_attendu', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('partiel', 'Partiel'), ('impaye', 'Impayé')], default='en_attente', max_length=20)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions_deces', to='gestion.association')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions_deces', to='gestion.dossierrapatriement')),
            ],
        ),
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('federation', 'Fédération'), ('association', 'Association')], max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('abreviation', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['type'], name='gestion_ent_type_3c842d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('type_document', models.CharField(blank=True, max_length=100)),
                ('visibilite', models.CharField(choices=[('association', 'Association seulement'), ('associations', 'Toutes les associations'), ('federation', 'Bureau fédéral seulement'), ('public', 'Public')], default='association', max_length=20)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('vu', 'Vu'), ('traite', 'Traité')], default='nouveau', max_length=20)),
                ('commentaire_traitement', models.TextField(blank=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('soumis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_traites', to=settings.AUTH_USER_MODEL)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.entite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureaux', to='gestion.entite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee', models.IntegerField()),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.entite')),
            ],
        ),
        migrations.AddField(
            model_name='association',
            name='entite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='association', to='gestion.entite'),
        ),
        migrations.AddField(
            model_name='association',
            name='federation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associations', to='gestion.entite'),
        ),
        migrations.AddField(
            model_name='affiliationassociation',
            name='federation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliations_associations', to='gestion.entite'),
        ),
        migrations.CreateModel(
            name='ActiviteCulturelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('capacite', models.PositiveIntegerField(blank=True, null=True)),
                ('reserve_aux_beneficiaires', models.BooleanField(default=True)),
                ('est_public', models.BooleanField(default=False)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_culturelles', to='gestion.entite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='gestion.entite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAdhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_evenement', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('commentaire', models.TextField(blank=True)),
                ('adhesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='gestion.adhesion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriqueEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinataire', models.EmailField(max_length=254)),
                ('type_email', models.CharField(choices=[('rappel_cotisation', 'Rappel cotisation'), ('confirmation_paiement', 'Confirmation paiement'), ('notification_activite', 'Notification activité')], max_length=30)),
                ('sujet', models.CharField(max_length=200)),
                ('succes', models.BooleanField(default=True)),
                ('commentaire', models.TextField(blank=True)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='gestion.activiteculturelle')),
                ('cotisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='gestion.cotisationassociationmensuelle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('type_information', models.CharField(choices=[('annonce', 'Annonce'), ('communique', 'Communiqué'), ('convocation', 'Convocation'), ('rappel', 'Rappel'), ('note', "Note d'information")], default='annonce', max_length=20)),
                ('priorite', models.CharField(choices=[('normale', 'Normale'), ('importante', 'Importante'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('date_fin_affichage', models.DateField(blank=True, null=True)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='informations/')),
                ('est_public', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='gestion.entite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('recette', 'Recette'), ('depense', 'Dépense')], max_length=10)),
                ('libelle', models.CharField(max_length=200)),
                ('montant_prevu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_realise', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion.budget')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('document', 'Document'), ('nouveaux_membres', 'Nouveaux membres'), ('information', 'Information')], max_length=30)),
                ('lu', models.BooleanField(default=False)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.document')),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.entite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('ville', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='unique_email_if_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='ParticipationActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gestion.activiteculturelle')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_activites', to='gestion.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.evenement')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.personne')),
            ],
        ),
        migrations.AddField(
            model_name='dossierrapatriement',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_rapatriement', to='gestion.personne'),
        ),
        migrations.CreateModel(
            name='BeneficiaireFederation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_activation', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('motif_desactivation', models.CharField(blank=True, max_length=255)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaires', to='gestion.affiliationassociation')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefices_federation', to='gestion.personne')),
            ],
        ),
        migrations.AddField(
            model_name='adhesion',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhesions', to='gestion.personne'),
        ),
        migrations.CreateModel(
            name='BureauMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adhesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.adhesion')),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='gestion.bureau')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.poste')),
            ],
        ),
        migrations.CreateModel(
            name='PersonneService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_activation', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='gestion.beneficiairefederation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.servicefederation')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('recette', 'Recette'), ('depense', 'Dépense')], max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('libelle', models.CharField(blank=True, max_length=200)),
                ('donateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.personne')),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.entite')),
                ('ligne_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.lignebudget')),
            ],
        ),
        migrations.CreateModel(
            name='UserEntiteRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.entite')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='cotisationassociationmensuelle',
            constraint=models.UniqueConstraint(fields=('affiliation', 'annee', 'mois'), name='unique_cotisation_mensuelle_par_affiliation'),
        ),
        migrations.AlterUniqueTogether(
            name='contributiondecesassociation',
            unique_together={('dossier', 'association')},
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('entite', 'annee'), name='unique_budget'),
        ),
        migrations.AddConstraint(
            model_name='affiliationassociation',
            constraint=models.UniqueConstraint(fields=('association', 'federation'), name='unique_affiliation_association_federation'),
        ),
        migrations.AddConstraint(
            model_name='participationactivite',
            constraint=models.UniqueConstraint(fields=('activite', 'personne'), name='unique_participation_activite'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('evenement', 'personne'), name='unique_participation'),
        ),
        migrations.AddConstraint(
            model_name='beneficiairefederation',
            constraint=models.UniqueConstraint(fields=('personne', 'affiliation'), name='unique_beneficiaire_par_affiliation'),
        ),
        migrations.AddIndex(
            model_name='adhesion',
            index=models.Index(fields=['statut'], name='gestion_adh_statut_7e1acf_idx'),
        ),
        migrations.AddConstraint(
            model_name='adhesion',
            constraint=models.UniqueConstraint(fields=('personne', 'association'), name='unique_personne_association'),
        ),
        migrations.AddConstraint(
            model_name='bureaumembre',
            constraint=models.UniqueConstraint(fields=('bureau', 'poste'), name='unique_poste_par_bureau'),
        ),
        migrations.AddConstraint(
            model_name='personneservice',
            constraint=models.UniqueConstraint(fields=('beneficiaire', 'service'), name='unique_service_par_beneficiaire'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='gestion_tra_date_1f480c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='gestion_tra_type_27e68a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userentiterole',
            unique_together={('user', 'entite', 'role')},
        ),
    ]
