# Generated by Django 6.0.4 on 2026-05-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_adhesion_date_validation_adhesion_valide_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activiteculturelle',
            name='description_de',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activiteculturelle',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activiteculturelle',
            name='description_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activiteculturelle',
            name='titre_de',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='activiteculturelle',
            name='titre_en',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='activiteculturelle',
            name='titre_fr',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='information',
            name='contenu_de',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='information',
            name='contenu_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='information',
            name='contenu_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='information',
            name='titre_de',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='information',
            name='titre_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='information',
            name='titre_fr',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
