# Generated by Django 6.0.4 on 2026-05-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_messagecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontact',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
