# Generated by Django 6.0.4 on 2026-05-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_messagecontact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesion',
            name='role',
            field=models.CharField(choices=[('membre', 'Membre'), ('president', 'Président'), ('membre_bureau', 'Membre du bureau')], default='membre', max_length=20),
        ),
    ]
