# Generated by Django 6.0.4 on 2026-05-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_information_envoyer_email_notification_destinataire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='envoyer_email',
            field=models.BooleanField(default=False, verbose_name='Envoyer une notification email'),
        ),
    ]
