# Generated by Django 6.0.4 on 2026-05-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_information_envoyer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='date_deces',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('decede', 'Decede')], default='actif', max_length=20),
        ),
    ]
