# Generated by Django 6.0.4 on 2026-05-09 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_personne_date_deces_personne_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierrapatriement',
            name='montant_participation_federation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dossierrapatriement',
            name='transaction_federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_rapatriement', to='gestion.transaction'),
        ),
    ]
