# Generated by Django 6.0.4 on 2026-05-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_dossierrapatriement_montant_participation_federation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='visibilite',
            field=models.CharField(choices=[('association', 'Association seulement'), ('associations', 'Toutes les associations'), ('federation', 'Bureau fédéral seulement')], default='association', max_length=20),
        ),
    ]
