# Generated by Django 6.0.4 on 2026-05-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_document_visibilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='visibilite',
            field=models.CharField(choices=[('association', 'Envoyé au bureau exécutif'), ('associations', 'partager aux associations'), ('federation', 'Réservé au bureau exécutif')], default='association', max_length=20),
        ),
    ]
