# Generated by Django 6.0.4 on 2026-05-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_document_visibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='personnes/'),
        ),
    ]
