# Generated by Django 6.0.4 on 2026-05-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_transaction_date_validation_transaction_validee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date_validation',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='validee',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='validee_par',
        ),
    ]
