# Generated by Django 6.0.4 on 2026-05-11 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_remove_transaction_date_validation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiairefederation',
            name='date_desactivation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiairefederation',
            name='date_reactivation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiairefederation',
            name='desactive_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaires_desactives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiairefederation',
            name='reactive_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaires_reactives', to=settings.AUTH_USER_MODEL),
        ),
    ]
