# Generated by Django 6.0.4 on 2026-05-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_beneficiairefederation_date_desactivation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='code_paiement',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
