# Generated by Django 6.0.4 on 2026-05-12 21:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_cotisationassociationmensuelle_date_modification_paiement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField(default=datetime.date.today)),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement'), ('cash', 'Espèces'), ('cheque', 'Chèque'), ('carte', 'Carte bancaire')], default='virement', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('commentaire', models.TextField(blank=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='gestion.association')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_associations_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
