# Generated by Django 6.0.4 on 2026-05-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_paiementassociation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementassociation',
            name='montant_affecte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paiementassociation',
            name='montant_avance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
