# Generated by Django 6.0.4 on 2026-05-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_paiementassociation_montant_affecte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierrapatriement',
            name='contributions_generees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dossierrapatriement',
            name='cout_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dossierrapatriement',
            name='montant_collecte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dossierrapatriement',
            name='montant_par_association',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dossierrapatriement',
            name='reste_a_collecter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
