# Generated by Django 6.0.4 on 2026-05-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_dossierrapatriement_contributions_generees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossierrapatriement',
            name='montant_participation_federation',
        ),
        migrations.RemoveField(
            model_name='dossierrapatriement',
            name='transaction_federation',
        ),
    ]
