ROLE_PERMISSIONS = {
    "federation_direction": {
        "associations_view",
        "associations_edit",
        "membres_view_all",
        "cotisations_view_all",
        "cotisations_edit",
        "cotisations_generate",
        "cotisations_export",
        "beneficiaires_view",
        "beneficiaires_edit",
        "rapatriements_view",
        "rapatriements_edit",
        "activites_view",
        "activites_create",
        "annonces_publish",
        "notifications_send",
        "documents_view",
        "documents_upload",
        "rapports_view",
        "emails_view",
        "transactions_view",
        "transactions_edit",
        "informations_view",
        "informations_publish",
        "membres_edit",
        "documents_traiter",
        "dashboard_view",
        "finance_override",
        "envoyer_rappel_deces_view",
        
    },
    "federation_finances": {
        "associations_view",
        "cotisations_view_all",
        "cotisations_edit",
        "cotisations_generate",
        "cotisations_export",
        "rapports_view",
        "emails_view",
        "transactions_view",
        "transactions_edit",
        "dashboard_view",
        "bureau_view",
        "rapatriements_view",
        "notifications_send",
        "rapatriements_edit",
        "finance_override",
        "envoyer_rappel_deces_view",
    },
    "federation_social": {
        "associations_view",
        "beneficiaires_view",
        "beneficiaires_edit",
        "rapatriements_view",
        "rapatriements_edit",
        "activites_view",
        "documents_view",
        "membres_edit",
        "bureau_view",
    },
    "federation_organisation": {
        "associations_view",
        "membres_view_all",
        "activites_view",
        "activites_create",
        "documents_view",
        "informations_view",
        "bureau_view",
    },
    "federation_projets": {
        "activites_view",
        "activites_create",
        "documents_view",
        "rapports_view",
        "bureau_view",
    },
    "federation_communication": {
        "notifications_send",
        "informations_view",
        "informations_publish",
        "bureau_view",
    },
    "federation_externe": {
        "associations_view",
        "activites_view",
        "documents_view",
    },
    "federation_lecture": {
        "associations_view",
        "membres_view_all",
        "cotisations_view_all",
        "beneficiaires_view",
        "rapatriements_view",
        "activites_view",
        "documents_view",
        "rapports_view",
        "emails_view",
        "informations_view",
    },
   "association_president": {
    "association_view_own",
    "membres_view_own",
    "membres_propose",
    "cotisations_view_own",
    "beneficiaires_view_own",
    "activites_view",
    "documents_view",
    "documents_upload",
    "informations_view",
    "transmettre_nouveaux_membres",
    "bureau_view",
    
},

"association_lecture": {
    "association_view_own",
    "membres_view_own",
    "cotisations_view_own",
    "beneficiaires_view_own",
    "activites_view",
    "documents_view",
    "informations_view",
},

}